### ISSUE TITLE
Incompatibility extended AST with comment lines (from Transonic) 

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/beniget#14]
Usually, there is no problem to use the extended AST with comment lines (defined in Transonic here https://bitbucket.org/fluiddyn/transonic/src/default/transonic/analyses/extast.py) in Beniget.

However, here is one case where there is a problem:

```
import beniget
from transonic.analyses.extast import parse

code = """
t = (
    "toto",
    # comment
    "titi",
)
"""

mod = parse(code)
duc = beniget.DefUseChains()
duc.visit(mod)
```

It gives:

```
Traceback (most recent call last):
  File "bug.py", line 16, in <module>
    duc.visit(mod)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/Dev/beniget/beniget/beniget.py", line 324, in visit_Module
    self.process_body(node.body)
  File "/home/pierre/Dev/beniget/beniget/beniget.py", line 275, in process_body
    self.visit(stmt)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/Dev/beniget/beniget/beniget.py", line 428, in visit_Assign
    dvalue = self.visit(node.value)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/Dev/beniget/beniget/beniget.py", line 844, in visit_List
    self.visit(elt).add_user(dnode)
AttributeError: 'NoneType' object has no attribute 'add_user'
```

i don't know what would be the correct way to fix that. 

- i could monkey patch beniget to add a visit for the CommentLine node. But it seems hacky. 

- The extended AST with comment lines could be defined deeper (with a cleaner implementation) and Beniget could handle the corresponding node.

- Or a quick fix in beniget...

**Comment by serge-sans-paille** [comment]
Closing the issue as subclassing is the right approach.
