### ISSUE TITLE
AttributeError indexing by Ellipsis

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/beniget#17]
This one is funny:

```
import gast as ast
import beniget
mod = ast.parse("var[...]")
du = beniget.DefUseChains()
du.visit(mod)
```
gives
```

Traceback (most recent call last):
  File "toto.py", line 7, in <module>
    du.visit(mod)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/Dev/beniget/beniget/beniget.py", line 329, in visit_Module
    self.process_body(node.body)
  File "/home/pierre/Dev/beniget/beniget/beniget.py", line 280, in process_body
    self.visit(stmt)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/Dev/beniget/beniget/beniget.py", line 657, in visit_Expr
    self.generic_visit(node)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 272, in generic_visit
    self.visit(value)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/Dev/beniget/beniget/beniget.py", line 790, in visit_Subscript
    self.visit(node.slice).add_user(dnode)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/Dev/beniget/beniget/beniget.py", line 739, in visit_Await
    self.visit(node.value).add_user(dnode)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 266, in generic_visit
    for field, value in iter_fields(node):
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 177, in iter_fields
    for field in node._fields:
AttributeError: 'NoneType' object has no attribute '_fields'
```

Why visit_Await?

Note that there is no problem with `var[Ellipsis]`

**Comment by serge-sans-paille** [comment]
This was fixed by 6315639adeccba7489cdb2101908ec33eca4be5d in gast.

`visit_Await` is referenced here because `Await` nodes have the same structure as `Index` nodes, but yeah, that's confusing.
