### ISSUE TITLE
test-suite failures on macOS

### ISSUE THREAD

**Issue by reneeotten** [serge-sans-paille/beniget#32]
first of all: thanks for maintaining this package!

When updating to the latest version in [MacPorts](https://macports.org), I am seeing now the following failures for the feature/tests that were recently added.

```
======================================================================
ERROR: test_named_expr_complex (tests.chains.TestDefUseChains)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/tests/chains.py", line 401, in test_named_expr_complex
    self.checkChains(
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/tests/chains.py", line 35, in checkChains
    c.visit(node)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/beniget/beniget.py", line 341, in visit_Module
    self.process_body(node.body)
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/beniget/beniget.py", line 292, in process_body
    self.visit(stmt)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/beniget/beniget.py", line 599, in visit_If
    self.visit(node.test)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 411, in generic_visit
    for field, value in iter_fields(node):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 249, in iter_fields
    for field in node._fields:
AttributeError: 'NoneType' object has no attribute '_fields'

======================================================================
ERROR: test_named_expr_simple (tests.chains.TestDefUseChains)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/tests/chains.py", line 392, in test_named_expr_simple
    self.checkChains(
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/tests/chains.py", line 35, in checkChains
    c.visit(node)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/beniget/beniget.py", line 341, in visit_Module
    self.process_body(node.body)
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/beniget/beniget.py", line 292, in process_body
    self.visit(stmt)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/beniget/beniget.py", line 599, in visit_If
    self.visit(node.test)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 411, in generic_visit
    for field, value in iter_fields(node):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 249, in iter_fields
    for field in node._fields:
AttributeError: 'NoneType' object has no attribute '_fields'

======================================================================
ERROR: test_named_expr_with_rename (tests.chains.TestDefUseChains)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/tests/chains.py", line 411, in test_named_expr_with_rename
    self.checkChains(
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/tests/chains.py", line 35, in checkChains
    c.visit(node)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/beniget/beniget.py", line 341, in visit_Module
    self.process_body(node.body)
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/beniget/beniget.py", line 292, in process_body
    self.visit(stmt)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1/beniget/beniget.py", line 599, in visit_If
    self.visit(node.test)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 411, in generic_visit
    for field, value in iter_fields(node):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 249, in iter_fields
    for field in node._fields:
AttributeError: 'NoneType' object has no attribute '_fields'

----------------------------------------------------------------------
Ran 145 tests in 0.200s

FAILED (errors=3)
Test failed: <unittest.runner.TextTestResult run=145 errors=3 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=145 errors=3 failures=0>
Command failed:  cd "/opt/local/var/macports/build/_Users_renee_Software_macports-ports_python_py-beniget/py39-beniget/work/beniget-0.4.1" && /opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 setup.py --no-user-cfg test
```

**Comment by serge-sans-paille** [comment]
Which version of gast are you using?

**Comment by reneeotten** [comment]
> Which version of gast are you using?

thank you for your response - I am using `gast` version 0.5.0

**Comment by serge-sans-paille** [comment]
that's the issue. `pip install -U gast` should fix the problem.

**Comment by reneeotten** [comment]
If you require a newer version of "gast", please have your requirements.txt reflect that. As downstream packagers (at least for MacPorts) we do not necessarily use "pip" and from the metadata you supplied version 0.5.0 should work.

**Comment by serge-sans-paille** [comment]
Sorry for the delay. It's just the test that tests a feature not supported by gast before 0.5.2. The code is still compatible with 0.5.0 and 0.5.1, so I didn't want to update the requirements. Does that make sense?

**Comment by serge-sans-paille** [comment]
On Thu, Aug 12, 2021 at 04:00:17PM -0700, Renee Otten wrote:
> that makes somewhat sense 😉. In that case though, you'd likely want to skip
> that test if the "gast" version isn't recent enough. That's easy enough to do
> when using "pytest", I'm not sure though from the top of my head on how to do
> that when using "unittest" framework.

Yeah, unfortunately, gast doesn't have a __version__ field (it now has on
master), so I can't rely on gast.__version__ to do the check :-/

**Comment by serge-sans-paille** [comment]
Closing as we should not experiment the issue with recent versions of beniget anymore. Let's bury this and reopen if it's still a problem.
